# Generated by Django 4.1.5 on 2023-01-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_comment_active_alter_comment_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post',
        ),
    ]
